version: '3'

services:
  app-server:
    build: .docker/php
    image: laravel-app
    depends_on:
      - mysql
    volumes:
      - ./:/application

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - ./.docker/mysql/.env
    volumes:
      - .docker/mysql/data:/var/lib/mysql

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "4443:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    depends_on:
      - app-server

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
